name: Swift Testing CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Swift Tests
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Show Swift Version
      run: swift --version

    - name: Run Swift Tests
      run: |
        cd /Users/runner/work/UWBViewerSystem/UWBViewerSystem/ios/UWBViewerSystem
        swift test --parallel

    - name: Test Summary
      if: always()
      run: echo "Swift Testing completed"

  format-check:
    name: Check Code Format
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install SwiftFormat
      run: brew install swiftformat

    - name: Check Format
      run: |
        swiftformat --lint --reporter github-actions-log .